#pragma once
#include "flowdaw/AppSettings.hpp"
#include "flowdaw/Wav.hpp"
#include <juce_gui_extra/juce_gui_extra.h>
#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <memory>
#include <string>
#include <vector>

namespace flowdaw::juceui {
class SampleBrowserComponent final : public juce::Component, private juce::ListBoxModel, private juce::KeyListener {
public:
    using ImportFn=std::function<void(const std::filesystem::path&)>; using PreviewFn=std::function<void(std::shared_ptr<AudioBuffer>)>; using StopPreviewFn=std::function<void()>; using SettingsChangedFn=std::function<void()>;
    SampleBrowserComponent(AppSettings&settings,ImportFn importFn,PreviewFn previewFn,StopPreviewFn stopPreviewFn,SettingsChangedFn settingsChanged):settings_(settings),importFn_(std::move(importFn)),previewFn_(std::move(previewFn)),stopPreviewFn_(std::move(stopPreviewFn)),settingsChanged_(std::move(settingsChanged)),list_("Samples",this),previewPool_(1){
        title_.setText("SAMPLE BROWSER",juce::dontSendNotification);title_.setFont(juce::Font(14.0f,juce::Font::bold));title_.setColour(juce::Label::textColourId,juce::Colour(0xfff5f2fb));addAndMakeVisible(title_);
        search_.setTextToShowWhenEmpty("Search WAVs...",juce::Colour(0xff817d91));search_.setColour(juce::TextEditor::backgroundColourId,juce::Colour(0xff11131d));search_.setColour(juce::TextEditor::textColourId,juce::Colour(0xfff5f2fb));search_.setColour(juce::TextEditor::outlineColourId,juce::Colour(0xff303044));search_.setColour(juce::TextEditor::focusedOutlineColourId,juce::Colour(0xff52d6c7));search_.onTextChange=[this]{refresh();};addAndMakeVisible(search_);
        root_.setTextWhenNothingSelected("No sample folder");root_.onChange=[this]{showRecent_=false;showFavorites_=false;recent_.setToggleState(false,juce::dontSendNotification);favoritesOnly_.setToggleState(false,juce::dontSendNotification);refresh();};addAndMakeVisible(root_);
        addRoot_.setButtonText("+ Folder");addRoot_.onClick=[this]{chooseRoot();};addAndMakeVisible(addRoot_);favorite_.setButtonText("Fav");favorite_.onClick=[this]{toggleFavoriteSelected();};addAndMakeVisible(favorite_);
        recent_.setButtonText("Recent");recent_.setClickingTogglesState(true);recent_.onClick=[this]{showRecent_=recent_.getToggleState();if(showRecent_){showFavorites_=false;favoritesOnly_.setToggleState(false,juce::dontSendNotification);}refresh();};addAndMakeVisible(recent_);
        favoritesOnly_.setButtonText("Favorites");favoritesOnly_.setClickingTogglesState(true);favoritesOnly_.onClick=[this]{showFavorites_=favoritesOnly_.getToggleState();if(showFavorites_){showRecent_=false;recent_.setToggleState(false,juce::dontSendNotification);}refresh();};addAndMakeVisible(favoritesOnly_);
        autoPreview_.setButtonText("Auto");autoPreview_.setClickingTogglesState(true);addAndMakeVisible(autoPreview_);import_.setButtonText("Import");import_.onClick=[this]{importSelected();};addAndMakeVisible(import_);preview_.setButtonText("Preview");preview_.onClick=[this]{previewSelected();};addAndMakeVisible(preview_);stopPreview_.setButtonText("Stop");stopPreview_.onClick=[this]{stopPreviewNow();};addAndMakeVisible(stopPreview_);
        for(auto*b:{&addRoot_,&favorite_,&recent_,&favoritesOnly_,&import_,&preview_,&stopPreview_}){b->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff1a1b2a));b->setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xff8f4cff));b->setColour(juce::TextButton::textColourOffId,juce::Colour(0xffbbb7c9));b->setColour(juce::TextButton::textColourOnId,juce::Colour(0xfff5f2fb));}
        autoPreview_.setColour(juce::ToggleButton::textColourId,juce::Colour(0xffbbb7c9));root_.setColour(juce::ComboBox::backgroundColourId,juce::Colour(0xff151622));root_.setColour(juce::ComboBox::textColourId,juce::Colour(0xfff5f2fb));root_.setColour(juce::ComboBox::outlineColourId,juce::Colour(0xff303044));root_.setColour(juce::ComboBox::arrowColourId,juce::Colour(0xff52d6c7));
        list_.setRowHeight(42);list_.setOutlineThickness(0);list_.setMultipleSelectionEnabled(false);list_.setColour(juce::ListBox::backgroundColourId,juce::Colour(0xff0c0f16));list_.addKeyListener(this);addAndMakeVisible(list_);search_.addKeyListener(this);
        hint_.setText("↑/↓ navigate  •  Space preview  •  Enter import  •  / search",juce::dontSendNotification);hint_.setColour(juce::Label::textColourId,juce::Colour(0xff817d91));hint_.setFont(10.5f);addAndMakeVisible(hint_);
        previewStatus_.setText("READY • Select a WAV to audition",juce::dontSendNotification);previewStatus_.setColour(juce::Label::textColourId,juce::Colour(0xff52d6c7));previewStatus_.setFont(juce::Font(10.5f,juce::Font::bold));addAndMakeVisible(previewStatus_);refreshRoots();refresh();
    }
    ~SampleBrowserComponent()override{previewGeneration_.fetch_add(1,std::memory_order_relaxed);previewPool_.removeAllJobs(true,5000);if(stopPreviewFn_)stopPreviewFn_();}
    void paint(juce::Graphics&g)override{
        auto b=getLocalBounds().toFloat();juce::ColourGradient bg(juce::Colour(0xff171322),b.getX(),b.getY(),juce::Colour(0xff090d13),b.getRight(),b.getBottom(),false);bg.addColour(0.48,juce::Colour(0xff10131d));g.setGradientFill(bg);g.fillRoundedRectangle(b.reduced(0.5f),10.0f);
        auto glow=b.reduced(1.0f);juce::ColourGradient edge(juce::Colour(0xff8f4cff).withAlpha(0.70f),glow.getX(),glow.getY(),juce::Colour(0xff52d6c7).withAlpha(0.34f),glow.getRight(),glow.getY(),false);g.setGradientFill(edge);g.drawRoundedRectangle(glow,10.0f,1.15f);
        g.setColour(juce::Colour(0xffe45b98).withAlpha(0.72f));g.fillRoundedRectangle(10.0f,12.0f,3.0f,18.0f,1.5f);
    }
    void resized()override{auto r=getLocalBounds().reduced(10);title_.setBounds(r.removeFromTop(26).withTrimmedLeft(9));r.removeFromTop(4);search_.setBounds(r.removeFromTop(32));r.removeFromTop(5);auto roots=r.removeFromTop(32);addRoot_.setBounds(roots.removeFromRight(78).reduced(2));root_.setBounds(roots.reduced(2));r.removeFromTop(4);auto actions=r.removeFromTop(32);import_.setBounds(actions.removeFromLeft(54).reduced(2));preview_.setBounds(actions.removeFromLeft(62).reduced(2));stopPreview_.setBounds(actions.removeFromLeft(48).reduced(2));favorite_.setBounds(actions.removeFromLeft(46).reduced(2));favoritesOnly_.setBounds(actions.removeFromLeft(72).reduced(2));recent_.setBounds(actions.removeFromLeft(58).reduced(2));autoPreview_.setBounds(actions.removeFromLeft(56).reduced(2));r.removeFromTop(5);previewStatus_.setBounds(r.removeFromBottom(20));hint_.setBounds(r.removeFromBottom(20));list_.setBounds(r.reduced(1));}
private:
    int getNumRows()override{return static_cast<int>(visible_.size());}
    void paintListBoxItem(int row,juce::Graphics&g,int width,int height,bool selected)override{
        if(row<0||row>=static_cast<int>(visible_.size()))return;const auto&p=visible_[static_cast<std::size_t>(row)];const bool favorite=std::find(settings_.favoriteSamples.begin(),settings_.favoriteSamples.end(),p)!=settings_.favoriteSamples.end();auto r=juce::Rectangle<float>(2.0f,2.0f,static_cast<float>(width)-4.0f,static_cast<float>(height)-4.0f);
        if(selected){juce::ColourGradient sel(juce::Colour(0xff8f4cff).withAlpha(0.42f),r.getX(),r.getY(),juce::Colour(0xff52d6c7).withAlpha(0.18f),r.getRight(),r.getBottom(),false);g.setGradientFill(sel);g.fillRoundedRectangle(r,6.0f);g.setColour(juce::Colour(0xff85e8dc).withAlpha(0.86f));g.drawRoundedRectangle(r,6.0f,1.0f);g.fillRoundedRectangle(r.getX(),r.getY()+5.0f,3.0f,r.getHeight()-10.0f,1.5f);}else if((row&1)!=0){g.setColour(juce::Colour(0xff151721).withAlpha(0.58f));g.fillRoundedRectangle(r,5.0f);}
        g.setColour(favorite?juce::Colour(0xffffbe63):juce::Colour(0xfff0edf6));g.setFont(juce::Font(11.5f,juce::Font::bold));g.drawText((favorite?juce::String::fromUTF8("★  "):juce::String("WAV  "))+juce::String(p.filename().string()),12,3,width-20,19,juce::Justification::centredLeft,true);g.setColour(juce::Colour(0xff817d91));g.setFont(10.0f);g.drawText(juce::String(p.parent_path().string()),12,21,width-20,std::max(12,height-22),juce::Justification::centredLeft,true);
    }
    void selectedRowsChanged(int)override{updateActions();if(autoPreview_.getToggleState()&&!selectedPath().empty())previewSelected();}
    void listBoxItemDoubleClicked(int row,const juce::MouseEvent&)override{if(row>=0&&row<static_cast<int>(visible_.size()))importPath(visible_[static_cast<std::size_t>(row)]);}
    juce::var getDragSourceDescription(const juce::SparseSet<int>&rows)override{if(rows.size()!=1)return{};const int row=rows[0];if(row<0||row>=static_cast<int>(visible_.size()))return{};return juce::String("flowdaw-sample:")+juce::String(visible_[static_cast<std::size_t>(row)].string());}
    bool keyPressed(const juce::KeyPress&key,juce::Component*)override{if(key==juce::KeyPress::spaceKey){previewSelected();return true;}if(key==juce::KeyPress::returnKey){importSelected();return true;}if(key==juce::KeyPress::escapeKey){stopPreviewNow();return true;}if(key.getKeyCode()==juce::KeyPress::upKey){selectRelative(-1);return true;}if(key.getKeyCode()==juce::KeyPress::downKey){selectRelative(1);return true;}if(key.getKeyCode()==juce::KeyPress::homeKey){selectAbsolute(0);return true;}if(key.getKeyCode()==juce::KeyPress::endKey){selectAbsolute(static_cast<int>(visible_.size())-1);return true;}if(key.getTextCharacter()=='/'){search_.grabKeyboardFocus();search_.selectAll();return true;}return false;}
    static std::string lower(std::string s){for(char&c:s)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return s;}
    bool matchesSearch(const std::filesystem::path&p)const{auto q=lower(search_.getText().trim().toStdString());return q.empty()||lower(p.filename().string()+" "+p.parent_path().string()).find(q)!=std::string::npos;}
    void notifySettingsChanged(){if(settingsChanged_)settingsChanged_();}
    void refreshRoots(){const int previous=root_.getSelectedId();root_.clear(juce::dontSendNotification);int id=1;for(const auto&p:settings_.sampleRoots)root_.addItem(juce::String(p.string()),id++);if(!settings_.sampleRoots.empty())root_.setSelectedId(previous>0&&previous<=static_cast<int>(settings_.sampleRoots.size())?previous:1,juce::dontSendNotification);}
    void refresh(){const auto previousPath=selectedPath();visible_.clear();if(showRecent_){for(const auto&p:settings_.recentSamples){std::error_code ec;if(std::filesystem::is_regular_file(p,ec)&&lower(p.extension().string())==".wav"&&matchesSearch(p))visible_.push_back(p);}}else if(showFavorites_){for(const auto&p:settings_.favoriteSamples){std::error_code ec;if(std::filesystem::is_regular_file(p,ec)&&lower(p.extension().string())==".wav"&&matchesSearch(p))visible_.push_back(p);}std::sort(visible_.begin(),visible_.end(),[](const auto&a,const auto&b){return lower(a.filename().string())<lower(b.filename().string());});}else{const int idx=root_.getSelectedId()-1;if(idx>=0&&idx<static_cast<int>(settings_.sampleRoots.size())){const auto base=settings_.sampleRoots[static_cast<std::size_t>(idx)];std::error_code ec;std::size_t scanned=0;if(std::filesystem::exists(base,ec))for(std::filesystem::recursive_directory_iterator it(base,std::filesystem::directory_options::skip_permission_denied,ec),end;it!=end&&scanned<5000;it.increment(ec)){if(ec){ec.clear();continue;}if(!it->is_regular_file(ec))continue;++scanned;if(lower(it->path().extension().string())!=".wav")continue;if(matchesSearch(it->path()))visible_.push_back(it->path());}std::sort(visible_.begin(),visible_.end(),[](const auto&a,const auto&b){return lower(a.filename().string())<lower(b.filename().string());});}}list_.updateContent();list_.repaint();if(!visible_.empty()){int row=0;if(!previousPath.empty()){auto it=std::find(visible_.begin(),visible_.end(),previousPath);if(it!=visible_.end())row=static_cast<int>(std::distance(visible_.begin(),it));}list_.selectRow(row);}else list_.deselectAllRows();updateActions();}
    void addRootPath(const std::filesystem::path&p){if(p.empty()||!std::filesystem::is_directory(p))return;if(std::find(settings_.sampleRoots.begin(),settings_.sampleRoots.end(),p)==settings_.sampleRoots.end()){settings_.sampleRoots.push_back(p);if(settings_.sampleRoots.size()>64)settings_.sampleRoots.erase(settings_.sampleRoots.begin());notifySettingsChanged();}showRecent_=false;showFavorites_=false;recent_.setToggleState(false,juce::dontSendNotification);favoritesOnly_.setToggleState(false,juce::dontSendNotification);refreshRoots();for(std::size_t i=0;i<settings_.sampleRoots.size();++i)if(settings_.sampleRoots[i]==p){root_.setSelectedId(static_cast<int>(i)+1,juce::dontSendNotification);break;}refresh();}
    void chooseRoot(){chooser_=std::make_unique<juce::FileChooser>("Add sample folder",juce::File::getSpecialLocation(juce::File::userMusicDirectory));chooser_->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectDirectories,[this](const juce::FileChooser&fc){auto f=fc.getResult();if(f.isDirectory())addRootPath(std::filesystem::path(f.getFullPathName().toStdString()));chooser_.reset();});}
    std::filesystem::path selectedPath()const{const int row=list_.getSelectedRow();return row>=0&&row<static_cast<int>(visible_.size())?visible_[static_cast<std::size_t>(row)]:std::filesystem::path{};}
    void selectAbsolute(int row){if(visible_.empty())return;row=std::clamp(row,0,static_cast<int>(visible_.size())-1);list_.selectRow(row);list_.scrollToEnsureRowIsOnscreen(row);updateActions();}void selectRelative(int d){if(visible_.empty())return;const int current=list_.getSelectedRow();selectAbsolute((current<0?0:current)+d);}
    void updateActions(){const bool selected=!selectedPath().empty();import_.setEnabled(selected);favorite_.setEnabled(selected);preview_.setEnabled(selected);favorite_.setButtonText(selected&&std::find(settings_.favoriteSamples.begin(),settings_.favoriteSamples.end(),selectedPath())!=settings_.favoriteSamples.end()?"★ Fav":"Fav");}
    void toggleFavoriteSelected(){auto p=selectedPath();if(p.empty())return;auto&f=settings_.favoriteSamples;auto it=std::find(f.begin(),f.end(),p);if(it==f.end()){f.push_back(p);if(f.size()>256)f.erase(f.begin());}else f.erase(it);notifySettingsChanged();list_.repaint();updateActions();}
    void previewSelected(){const auto path=selectedPath();if(path.empty()||!previewFn_)return;const auto generation=previewGeneration_.fetch_add(1,std::memory_order_relaxed)+1;previewStatus_.setColour(juce::Label::textColourId,juce::Colour(0xffffbe63));previewStatus_.setText("LOADING • "+juce::String(path.filename().string()),juce::dontSendNotification);previewPool_.removeAllJobs(false,0);auto safe=juce::Component::SafePointer<SampleBrowserComponent>(this);previewPool_.addJob([safe,path,generation]{try{auto audio=std::make_shared<AudioBuffer>(WavFile::read(path));juce::MessageManager::callAsync([safe,path,generation,audio]{if(auto*self=safe.getComponent()){if(self->previewGeneration_.load(std::memory_order_relaxed)!=generation)return;if(audio&&audio->frames()>0&&self->previewFn_)self->previewFn_(audio);const double seconds=audio&&audio->sampleRate>0?static_cast<double>(audio->frames())/audio->sampleRate:0.0;self->previewStatus_.setColour(juce::Label::textColourId,juce::Colour(0xff52d6c7));self->previewStatus_.setText("PLAYING • "+juce::String(path.filename().string())+" • "+juce::String(seconds,1)+"s • "+juce::String(audio?audio->sampleRate:0)+" Hz",juce::dontSendNotification);}});}catch(const std::exception&e){const juce::String error=e.what();juce::MessageManager::callAsync([safe,generation,error]{if(auto*self=safe.getComponent()){if(self->previewGeneration_.load(std::memory_order_relaxed)!=generation)return;self->previewStatus_.setColour(juce::Label::textColourId,juce::Colour(0xffff667d));self->previewStatus_.setText("ERROR • "+error,juce::dontSendNotification);}});}});}
    void stopPreviewNow(){previewGeneration_.fetch_add(1,std::memory_order_relaxed);if(stopPreviewFn_)stopPreviewFn_();previewStatus_.setColour(juce::Label::textColourId,juce::Colour(0xff817d91));previewStatus_.setText("STOPPED • Preview idle",juce::dontSendNotification);}
    void importPath(const std::filesystem::path&p){if(p.empty()||!std::filesystem::exists(p)||!importFn_)return;importFn_(p);auto&r=settings_.recentSamples;r.erase(std::remove(r.begin(),r.end(),p),r.end());r.insert(r.begin(),p);if(r.size()>64)r.resize(64);notifySettingsChanged();if(showRecent_)refresh();}void importSelected(){importPath(selectedPath());}
    AppSettings&settings_;ImportFn importFn_;PreviewFn previewFn_;StopPreviewFn stopPreviewFn_;SettingsChangedFn settingsChanged_;std::vector<std::filesystem::path>visible_;std::unique_ptr<juce::FileChooser>chooser_;bool showRecent_=false,showFavorites_=false;std::atomic<std::uint64_t>previewGeneration_{0};juce::ThreadPool previewPool_;juce::Label title_,hint_,previewStatus_;juce::TextEditor search_;juce::ComboBox root_;juce::TextButton addRoot_,favorite_,recent_,favoritesOnly_,import_,preview_,stopPreview_;juce::ToggleButton autoPreview_;juce::ListBox list_;
};
}