#define FLOWDAW_EMBED_PHASE3 1
#include "main_phase3.cpp"
#undef FLOWDAW_EMBED_PHASE3

#include "flowdaw/Automation.hpp"
#include "flowdaw/Export.hpp"

namespace {
struct Phase4App:Phase3App{
 bool mixerMode=false,audioRecording=false;int mixerTrackIndex=0,mixerBusIndex=0;Tick audioRecordStartTick=0;Project audioRecordBefore;
 Rect mixerToggle{25,334,170,28},trackPrev{245,365,30,26},trackNext{455,365,30,26},volMinus4{505,365,28,26},volPlus4{589,365,28,26},panMinus4{635,365,28,26},panPlus4{719,365,28,26},mute4{760,365,55,26},solo4{820,365,55,26},arm4{880,365,55,26},monitor4{940,365,72,26},recAudio4{1020,365,100,26},takePrev4{1130,365,30,26},takeNext4{1235,365,30,26};
 Rect route4{245,405,150,26},sendMinus4{405,405,28,26},sendPlus4{489,405,28,26},newBus4{530,405,90,26},busPrev4{630,405,28,26},busNext4{714,405,28,26},busVolMinus4{755,405,28,26},busVolPlus4{839,405,28,26},autoVol4{885,405,95,26},autoPan4{988,405,95,26},clearAuto4{1091,405,95,26},exportMix4{1195,405,95,26},exportStems4{1298,405,110,26};
 Rect mixerPanel()const{return{browserW+8,seqY-12,W-browserW-18,H-seqY-52};}
 Track*selectedMixerTrack(){if(project.tracks.empty())return nullptr;mixerTrackIndex=std::clamp(mixerTrackIndex,0,static_cast<int>(project.tracks.size())-1);return &project.tracks[static_cast<std::size_t>(mixerTrackIndex)];}
 Bus*selectedMixerBus(){if(project.buses.empty())return nullptr;mixerBusIndex=std::clamp(mixerBusIndex,0,static_cast<int>(project.buses.size())-1);return &project.buses[static_cast<std::size_t>(mixerBusIndex)];}
 void toggleMixer(){mixerMode=!mixerMode;if(mixerMode)pianoMode=false;status=mixerMode?"Mixer / Recording / Automation":"Main production view";}
 void cycleTrack(int dlt){if(project.tracks.empty())return;mixerTrackIndex=(mixerTrackIndex+dlt+static_cast<int>(project.tracks.size()))%static_cast<int>(project.tracks.size());}
 void editTrack(float dv,float dp){auto*t=selectedMixerTrack();if(!t)return;Project before=project;t->mixer.volume=std::clamp(t->mixer.volume+dv,0.0f,2.0f);t->mixer.pan=std::clamp(t->mixer.pan+dp,-1.0f,1.0f);commit(std::move(before),"Edit mixer channel");}
 void toggleTrackFlag(int which){auto*t=selectedMixerTrack();if(!t)return;Project before=project;if(which==0)t->mixer.mute=!t->mixer.mute;else if(which==1)t->mixer.solo=!t->mixer.solo;else if(which==2)t->armed=!t->armed;else{t->inputMonitor=!t->inputMonitor;engine.setInputMonitoring(t->inputMonitor);}commit(std::move(before),"Edit track state");}
 void addBus(){Project before=project;Bus b;b.name="BUS "+std::to_string(project.buses.size()+1);project.buses.push_back(b);mixerBusIndex=static_cast<int>(project.buses.size())-1;commit(std::move(before),"Add mixer bus");status="Created "+project.buses.back().name;}
 void cycleBus(int dlt){if(project.buses.empty()){addBus();return;}mixerBusIndex=(mixerBusIndex+dlt+static_cast<int>(project.buses.size()))%static_cast<int>(project.buses.size());}
 void adjustBus(float dv){auto*b=selectedMixerBus();if(!b){addBus();b=selectedMixerBus();}if(!b)return;Project before=project;b->mixer.volume=std::clamp(b->mixer.volume+dv,0.0f,2.0f);commit(std::move(before),"Edit bus fader");}
 void cycleRoute(){auto*t=selectedMixerTrack();if(!t)return;if(project.buses.empty()){addBus();t=selectedMixerTrack();}Project before=project;if(t->outputBusId==0)t->outputBusId=project.buses.front().id;else{int idx=-1;for(int i=0;i<static_cast<int>(project.buses.size());++i)if(project.buses[static_cast<std::size_t>(i)].id==t->outputBusId)idx=i;t->outputBusId=(idx<0||idx+1>=static_cast<int>(project.buses.size()))?0:project.buses[static_cast<std::size_t>(idx+1)].id;}commit(std::move(before),"Route track");}
 MixerSend*selectedSend(){auto*t=selectedMixerTrack();auto*b=selectedMixerBus();if(!t||!b)return nullptr;for(auto&s:t->sends)if(s.busId==b->id)return&s;return nullptr;}
 void adjustSend(float dv){auto*t=selectedMixerTrack();if(!t)return;if(project.buses.empty())addBus();t=selectedMixerTrack();auto*b=selectedMixerBus();if(!t||!b)return;Project before=project;auto*s=selectedSend();if(!s){MixerSend ns;ns.busId=b->id;ns.gain=0.0f;t->sends.push_back(ns);s=&t->sends.back();}s->gain=std::clamp(s->gain+dv,0.0f,2.0f);commit(std::move(before),"Edit send level");}
 void addAutomationPoint(const std::string&target){auto*t=selectedMixerTrack();if(!t)return;Project before=project;AutomationLane*lane=nullptr;for(auto&l:project.automation)if(l.target==target&&l.targetId==t->id){lane=&l;break;}if(!lane){AutomationLane l;l.target=target;l.targetId=t->id;project.automation.push_back(l);lane=&project.automation.back();}AutomationPoint pt;pt.tick=std::max<Tick>(0,playheadTick());pt.value=target=="track.pan"?t->mixer.pan:t->mixer.volume;lane->points.push_back(pt);normalizeAutomationLane(*lane);commit(std::move(before),"Write automation point");status="Automation point @ "+std::to_string(pt.tick)+" ticks";}
 void clearTrackAutomation(){auto*t=selectedMixerTrack();if(!t)return;Project before=project;project.automation.erase(std::remove_if(project.automation.begin(),project.automation.end(),[&](auto const&l){return l.targetId==t->id&&(l.target=="track.volume"||l.target=="track.pan");}),project.automation.end());commit(std::move(before),"Clear track automation");}
 Track*recordTrack(){for(auto&t:project.tracks)if(t.armed)return&t;for(auto&t:project.tracks)if(t.name=="VOCAL"){t.armed=true;return&t;}Track t;t.name="VOCAL";t.armed=true;project.tracks.push_back(t);mixerTrackIndex=static_cast<int>(project.tracks.size())-1;return&project.tracks.back();}
 void toggleAudioRecording(){
    if(!audioRecording){if(!engine.inputAvailable()){status="No default audio input device; connect/select a microphone";return;}Project before=project;auto*t=recordTrack();if(!t)return;audioRecordBefore=before;audioRecordStartTick=playheadTick();engine.setInputMonitoring(t->inputMonitor);if(!engine.beginRecording(static_cast<SampleIndex>(project.sampleRate)*60*10)){status="Could not arm audio recorder";return;}audioRecording=true;if(!engine.isPlaying())engine.play();status="REC AUDIO - recording into "+t->name;return;}
    auto captured=engine.finishRecording();audioRecording=false;if(captured.frames()<32){project=audioRecordBefore;publish();status="Empty audio take discarded";return;}auto*t=recordTrack();if(!t)return;SampleAsset asset;asset.name="Audio Take "+std::to_string(t->takes.size()+1);asset.audio=std::make_shared<AudioBuffer>(captured);auto base=projectPath.has_parent_path()?projectPath.parent_path():std::filesystem::path(".");auto dir=base/"recordings";std::filesystem::create_directories(dir);asset.path=std::filesystem::absolute(dir/("take_"+std::to_string(asset.id)+".wav"));WavFile::writeFloat32(asset.path,captured);const Id sampleId=asset.id;project.samples.push_back(asset);t=recordTrack();RecordingTake take;take.name="Take "+std::to_string(t->takes.size()+1);take.sampleId=sampleId;take.startTick=audioRecordStartTick;take.lengthTicks=MusicalTime::samplesToTicks(captured.frames(),project.transport.bpm,captured.sampleRate);t->takes.push_back(take);t->activeTakeId=take.id;undo.commit(audioRecordBefore,project,"Record audio take");publish();status="Recorded "+take.name+" ("+std::to_string(captured.frames())+" frames)";
 }
 void cycleTake(int dlt){auto*t=selectedMixerTrack();if(!t||t->takes.empty())return;int idx=0;for(int i=0;i<static_cast<int>(t->takes.size());++i)if(t->takes[static_cast<std::size_t>(i)].id==t->activeTakeId)idx=i;idx=(idx+dlt+static_cast<int>(t->takes.size()))%static_cast<int>(t->takes.size());Project before=project;t->activeTakeId=t->takes[static_cast<std::size_t>(idx)].id;commit(std::move(before),"Select recording take");status="Comp active: "+t->takes[static_cast<std::size_t>(idx)].name;}
 std::string routeLabel(const Track&t)const{if(!t.outputBusId)return"OUT: MASTER";auto*b=project.findBus(t.outputBusId);return b?"OUT: "+b->name:"OUT: MASTER";}
 void exportMix(){try{auto base=projectPath.has_parent_path()?projectPath.parent_path():std::filesystem::path(".");std::string stem=projectPath.stem().string();if(stem.empty()||stem=="Untitled")stem="FLOWDAW";auto path=base/(stem+"_mix.wav");exportProjectWav(project,path,2.0);status="Exported "+path.string();}catch(const std::exception&e){status=std::string("Export failed: ")+e.what();}}
 void exportStems(){try{auto base=projectPath.has_parent_path()?projectPath.parent_path():std::filesystem::path(".");auto paths=exportTrackStems(project,base/"stems",2.0);status="Exported "+std::to_string(paths.size())+" stems";}catch(const std::exception&e){status=std::string("Stem export failed: ")+e.what();}}
 void drawMixer(){
    const auto panel=rgb(d,24,26,31),panel2=rgb(d,39,42,50),txt=rgb(d,232,234,239),muted=rgb(d,145,151,163),green=rgb(d,47,202,132),red=rgb(d,225,72,78),blue=rgb(d,61,143,230),orange=rgb(d,235,151,62),purple=rgb(d,101,80,220),grid=rgb(d,56,61,70);
    fill(d,win,gc,mixerToggle,mixerMode?purple:panel2);text(d,win,gc,mixerToggle.x+10,mixerToggle.y+19,mixerMode?"CLOSE MIXER":"MIXER / REC [M]",txt);if(!mixerMode){XFlush(d);return;}auto box=mixerPanel();fill(d,win,gc,box,panel);auto*t=selectedMixerTrack();if(!t)return;auto button=[&](Rect r,const std::string&s,unsigned long c=0UL){fill(d,win,gc,r,c?c:panel2);text(d,win,gc,r.x+6,r.y+18,s,txt);};
    text(d,win,gc,box.x+14,box.y+25,"PHASE 4 MIXER / RECORDING / AUTOMATION",muted);button(trackPrev,"<");button(trackNext,">");text(d,win,gc,282,383,"TRACK "+std::to_string(mixerTrackIndex+1)+"  "+shortName(t->name,18),txt);button(volMinus4,"-");button(volPlus4,"+");text(d,win,gc,538,383,"VOL "+std::to_string(static_cast<int>(t->mixer.volume*100)),muted);button(panMinus4,"-");button(panPlus4,"+");text(d,win,gc,668,383,"PAN "+std::to_string(static_cast<int>(t->mixer.pan*100)),muted);button(mute4,"MUTE",t->mixer.mute?red:panel2);button(solo4,"SOLO",t->mixer.solo?green:panel2);button(arm4,"ARM",t->armed?red:panel2);button(monitor4,"MON",t->inputMonitor?green:panel2);button(recAudio4,audioRecording?"STOP REC":"REC AUDIO",audioRecording?red:blue);button(takePrev4,"<");button(takeNext4,">");text(d,win,gc,1166,383,"TAKE "+std::to_string(t->takes.size()),muted);
    button(route4,routeLabel(*t),blue);button(sendMinus4,"-");button(sendPlus4,"+");auto*s=selectedSend();text(d,win,gc,438,423,"SEND "+std::to_string(s?static_cast<int>(s->gain*100):0),muted);button(newBus4,"NEW BUS");button(busPrev4,"<");button(busNext4,">");auto*b=selectedMixerBus();text(d,win,gc,665,423,b?shortName(b->name,12):"NO BUS",muted);button(busVolMinus4,"-");button(busVolPlus4,"+");text(d,win,gc,788,423,"BUS "+std::to_string(b?static_cast<int>(b->mixer.volume*100):0),muted);button(autoVol4,"AUTO VOL",orange);button(autoPan4,"AUTO PAN",orange);button(clearAuto4,"CLR AUTO");button(exportMix4,"EXPORT WAV",green);button(exportStems4,"STEMS",green);
    int y=455;for(int i=0;i<static_cast<int>(project.tracks.size())&&i<8;++i){auto const&tr=project.tracks[static_cast<std::size_t>(i)];Rect strip{245+i*145,y,132,205};fill(d,win,gc,strip,i==mixerTrackIndex?rgb(d,48,52,62):panel2);text(d,win,gc,strip.x+8,strip.y+20,shortName(tr.name,15),txt);text(d,win,gc,strip.x+8,strip.y+42,"VOL "+std::to_string(static_cast<int>(tr.mixer.volume*100)),muted);text(d,win,gc,strip.x+8,strip.y+62,"PAN "+std::to_string(static_cast<int>(tr.mixer.pan*100)),muted);text(d,win,gc,strip.x+8,strip.y+82,tr.armed?"ARMED":"",tr.armed?red:muted);text(d,win,gc,strip.x+8,strip.y+102,"TAKES "+std::to_string(tr.takes.size()),muted);text(d,win,gc,strip.x+8,strip.y+122,routeLabel(tr),muted);int meterH=55;int mh=static_cast<int>(std::clamp(tr.mixer.volume/2.0f,0.0f,1.0f)*meterH);fill(d,win,gc,{strip.x+100,strip.y+137,14,meterH},grid);fill(d,win,gc,{strip.x+100,strip.y+137+meterH-mh,14,mh},green);}
    int ay=690;text(d,win,gc,245,ay,"Automation (selected track volume):",muted);const AutomationLane*lane=findAutomation(project,"track.volume",t->id);Rect ar{485,ay-16,720,80};fill(d,win,gc,ar,rgb(d,20,22,27));line(d,win,gc,ar.x,ar.y+ar.h/2,ar.x+ar.w,ar.y+ar.h/2,grid);if(lane&&lane->points.size()>0){Tick maxTick=std::max<Tick>(kPPQ*8,lane->points.back().tick);for(std::size_t i=0;i<lane->points.size();++i){auto const&pnt=lane->points[i];int x=ar.x+static_cast<int>(static_cast<double>(pnt.tick)/maxTick*ar.w);int yy=ar.y+ar.h-static_cast<int>(std::clamp(pnt.value/2.0f,0.0f,1.0f)*ar.h);fill(d,win,gc,{x-3,yy-3,7,7},orange);if(i){auto const&prev=lane->points[i-1];int px=ar.x+static_cast<int>(static_cast<double>(prev.tick)/maxTick*ar.w);int py=ar.y+ar.h-static_cast<int>(std::clamp(prev.value/2.0f,0.0f,1.0f)*ar.h);line(d,win,gc,px,py,x,yy,orange);}}}text(d,win,gc,245,805,"REC uses the armed track. AUTO VOL/PAN writes current value at the playhead. TAKE arrows switch the non-destructive comp.",muted);XFlush(d);
 }
 void drawPhase4(){Phase3App::drawPhase3();drawMixer();}
 void handlePhase4Key(XKeyEvent&k){if(inputMode!=InputMode::Idle){Phase3App::handleMidiKey(k);return;}KeySym ks=XLookupKeysym(&k,0);if(ks==XK_m||ks==XK_M){toggleMixer();return;}if(ks==XK_F9){toggleAudioRecording();return;}if(!mixerMode){Phase3App::handleMidiKey(k);return;}if(ks==XK_Left){cycleTrack(-1);return;}if(ks==XK_Right){cycleTrack(1);return;}if(ks==XK_Up){editTrack(.05f,0);return;}if(ks==XK_Down){editTrack(-.05f,0);return;}if(ks==XK_space||((k.state&ControlMask)!=0)){Phase3App::handleMidiKey(k);return;}}
 void handlePhase4Button(XButtonEvent&e){if(mixerToggle.contains(e.x,e.y)){if(e.button==1)toggleMixer();return;}if(!mixerMode){Phase3App::handleMidiButton(e);return;}if(e.button!=1)return;if(trackPrev.contains(e.x,e.y)){cycleTrack(-1);return;}if(trackNext.contains(e.x,e.y)){cycleTrack(1);return;}if(volMinus4.contains(e.x,e.y)){editTrack(-.05f,0);return;}if(volPlus4.contains(e.x,e.y)){editTrack(.05f,0);return;}if(panMinus4.contains(e.x,e.y)){editTrack(0,-.1f);return;}if(panPlus4.contains(e.x,e.y)){editTrack(0,.1f);return;}if(mute4.contains(e.x,e.y)){toggleTrackFlag(0);return;}if(solo4.contains(e.x,e.y)){toggleTrackFlag(1);return;}if(arm4.contains(e.x,e.y)){toggleTrackFlag(2);return;}if(monitor4.contains(e.x,e.y)){toggleTrackFlag(3);return;}if(recAudio4.contains(e.x,e.y)){toggleAudioRecording();return;}if(takePrev4.contains(e.x,e.y)){cycleTake(-1);return;}if(takeNext4.contains(e.x,e.y)){cycleTake(1);return;}if(route4.contains(e.x,e.y)){cycleRoute();return;}if(sendMinus4.contains(e.x,e.y)){adjustSend(-.05f);return;}if(sendPlus4.contains(e.x,e.y)){adjustSend(.05f);return;}if(newBus4.contains(e.x,e.y)){addBus();return;}if(busPrev4.contains(e.x,e.y)){cycleBus(-1);return;}if(busNext4.contains(e.x,e.y)){cycleBus(1);return;}if(busVolMinus4.contains(e.x,e.y)){adjustBus(-.05f);return;}if(busVolPlus4.contains(e.x,e.y)){adjustBus(.05f);return;}if(autoVol4.contains(e.x,e.y)){addAutomationPoint("track.volume");return;}if(autoPan4.contains(e.x,e.y)){addAutomationPoint("track.pan");return;}if(clearAuto4.contains(e.x,e.y)){clearTrackAutomation();return;}if(exportMix4.contains(e.x,e.y)){exportMix();return;}if(exportStems4.contains(e.x,e.y)){exportStems();return;}int y=455;for(int i=0;i<static_cast<int>(project.tracks.size())&&i<8;++i){Rect strip{245+i*145,y,132,205};if(strip.contains(e.x,e.y)){mixerTrackIndex=i;return;}}}
 void handlePhase4Motion(XMotionEvent&e){if(!mixerMode)Phase3App::handleMidiMotion(e);}
 void handlePhase4Release(){if(!mixerMode)Phase3App::handleMidiRelease();}
 int runPhase4(int argc,char**argv){d=XOpenDisplay(nullptr);if(!d){std::cerr<<"Cannot open X display\n";return 2;}int scr=DefaultScreen(d);win=XCreateSimpleWindow(d,RootWindow(d,scr),30,30,W,H,0,0,rgb(d,16,17,20));XStoreName(d,win,"FLOWDAW - Phase 4 Recording / Automation / Mixer");gc=XCreateGC(d,win,0,nullptr);XSelectInput(d,win,ExposureMask|KeyPressMask|ButtonPressMask|ButtonReleaseMask|PointerMotionMask|StructureNotifyMask);XMapWindow(d,win);bool audioOk=engine.open(project.sampleRate,256);status=audioOk?(engine.inputAvailable()?"Audio input/output ready | M opens Mixer":"Audio output ready; no input device | M opens Mixer"):"No physical audio device; offline engine active | M opens Mixer";publish();if(argc>1){std::filesystem::path path=argv[1];if(path.extension()==".flow")openProject(path);else importWav(path);ensureMidiPattern();}using namespace std::chrono_literals;while(running){while(XPending(d)){XEvent e;XNextEvent(d,&e);if(e.type==Expose)drawPhase4();else if(e.type==KeyPress)handlePhase4Key(e.xkey);else if(e.type==ButtonPress)handlePhase4Button(e.xbutton);else if(e.type==MotionNotify)handlePhase4Motion(e.xmotion);else if(e.type==ButtonRelease)handlePhase4Release();else if(e.type==DestroyNotify)running=false;}drawPhase4();std::this_thread::sleep_for(16ms);}if(audioRecording)toggleAudioRecording();if(recordingChops)finishChopRecording();engine.close();XFreeGC(d,gc);XDestroyWindow(d,win);XCloseDisplay(d);return 0;}
};
}
#ifndef FLOWDAW_EMBED_PHASE4
int main(int argc,char**argv){Phase4App app;return app.runPhase4(argc,argv);}
#endif
