#define main flowdaw_phase4_embedded_main
#include "main_phase4.cpp"
#undef main

#include "flowdaw/PluginHost.hpp"
#include "flowdaw/ProductionAssistant.hpp"
#include "flowdaw/Workflow.hpp"
#include <cstdlib>

namespace {
struct Phase5App:Phase4App{
 bool phase5Mode=false;int suggestionIndex=0,commandIndex=0,masterPluginIndex=0,discoveredIndex=0;
 std::vector<AssistantSuggestion> suggestions;std::vector<ProjectHealthIssue> healthIssues;std::vector<WorkflowCommand> commands;std::vector<PluginDescriptor> discovered;
 Rect phase5Toggle{25,366,170,28},suggestPrev{245,395,30,26},suggestNext{365,395,30,26},applySuggest{405,395,115,26},healthButton{530,395,100,26},scanButton{640,395,110,26},addExternal{760,395,115,26};
 Rect masterGain{245,435,110,26},masterClip{365,435,125,26},masterWidth{500,435,120,26},trackGain{630,435,115,26},pluginPrev{755,435,30,26},pluginNext{870,435,30,26},pluginBypass{910,435,95,26},pluginRemove{1015,435,95,26};
 Rect commandPrev{245,720,30,26},commandNext{365,720,30,26},commandRun{405,720,110,26};
 Rect phase5Panel()const{return{browserW+8,seqY-12,W-browserW-18,H-seqY-52};}
 void refreshPhase5(){suggestions=analyzeProductionContext(project);healthIssues=validateProject(project);commands=workflowCommands();if(suggestions.empty())suggestionIndex=0;else suggestionIndex=std::clamp(suggestionIndex,0,static_cast<int>(suggestions.size())-1);if(commands.empty())commandIndex=0;else commandIndex=std::clamp(commandIndex,0,static_cast<int>(commands.size())-1);if(project.master.plugins.empty())masterPluginIndex=0;else masterPluginIndex=std::clamp(masterPluginIndex,0,static_cast<int>(project.master.plugins.size())-1);}
 void togglePhase5(){phase5Mode=!phase5Mode;if(phase5Mode){mixerMode=false;pianoMode=false;refreshPhase5();status="Assist / Plugins / Workflow";}else status="Main production view";}
 AssistantSuggestion* selectedSuggestion(){if(suggestions.empty())return nullptr;suggestionIndex=(suggestionIndex+static_cast<int>(suggestions.size()))%static_cast<int>(suggestions.size());return&suggestions[static_cast<std::size_t>(suggestionIndex)];}
 WorkflowCommand* selectedCommand(){if(commands.empty())return nullptr;commandIndex=(commandIndex+static_cast<int>(commands.size()))%static_cast<int>(commands.size());return&commands[static_cast<std::size_t>(commandIndex)];}
 PluginInstance* selectedMasterPlugin(){if(project.master.plugins.empty())return nullptr;masterPluginIndex=std::clamp(masterPluginIndex,0,static_cast<int>(project.master.plugins.size())-1);return&project.master.plugins[static_cast<std::size_t>(masterPluginIndex)];}
 void cycleSuggestion(int d){if(suggestions.empty())return;suggestionIndex=(suggestionIndex+d+static_cast<int>(suggestions.size()))%static_cast<int>(suggestions.size());}
 void cycleCommand(int d){if(commands.empty())return;commandIndex=(commandIndex+d+static_cast<int>(commands.size()))%static_cast<int>(commands.size());}
 void cycleMasterPlugin(int d){if(project.master.plugins.empty())return;masterPluginIndex=(masterPluginIndex+d+static_cast<int>(project.master.plugins.size()))%static_cast<int>(project.master.plugins.size());}
 void applySelectedSuggestion(){auto*s=selectedSuggestion();if(!s){status="Project assistant found no current suggestions";return;}if(s->action==AssistantAction::None){status=s->detail;return;}Project before=project;std::string result;if(!applyAssistantSuggestion(project,*s,result)){project=before;status=result;return;}commit(std::move(before),"Assistant: "+s->title);status=result+" | Undo available";refreshPhase5();}
 void addMasterBuiltin(const std::string&id){Project before=project;project.master.plugins.push_back(makeBuiltinPlugin(id));masterPluginIndex=static_cast<int>(project.master.plugins.size())-1;commit(std::move(before),"Add master plugin");status="Added "+project.master.plugins.back().name+" to master";refreshPhase5();}
 void addTrackGainPlugin(){auto*t=selectedMixerTrack();if(!t){status="No track selected";return;}Project before=project;t->mixer.plugins.push_back(makeBuiltinPlugin("flow.gain"));commit(std::move(before),"Add track plugin");status="Added FLOW Gain to "+t->name;refreshPhase5();}
 void toggleMasterPluginBypass(){auto*p=selectedMasterPlugin();if(!p)return;Project before=project;p->bypass=!p->bypass;commit(std::move(before),"Bypass master plugin");status=p->name+(p->bypass?" bypassed":" active");refreshPhase5();}
 void removeMasterPlugin(){auto*p=selectedMasterPlugin();if(!p)return;Project before=project;auto name=p->name;project.master.plugins.erase(project.master.plugins.begin()+masterPluginIndex);commit(std::move(before),"Remove master plugin");status="Removed "+name;refreshPhase5();}
 void scanExternalPlugins(){std::vector<std::filesystem::path> roots;const char*home=std::getenv("HOME");if(home){roots.emplace_back(std::filesystem::path(home)/".vst3");roots.emplace_back(std::filesystem::path(home)/"Library/Audio/Plug-Ins/VST3");roots.emplace_back(std::filesystem::path(home)/"Library/Audio/Plug-Ins/Components");}roots.emplace_back("/usr/lib/vst3");roots.emplace_back("/usr/local/lib/vst3");roots.emplace_back("/Library/Audio/Plug-Ins/VST3");roots.emplace_back("/Library/Audio/Plug-Ins/Components");discovered=scanPluginPaths(roots);discoveredIndex=0;status="Plugin scan found "+std::to_string(discovered.size())+" VST3/AU bundles (discovery only; no binary loaded)";}
 void addDiscoveredPluginSlot(){if(discovered.empty()){status="Scan first; no external plugins discovered";return;}auto*t=selectedMixerTrack();if(!t){status="No track selected";return;}discoveredIndex=std::clamp(discoveredIndex,0,static_cast<int>(discovered.size())-1);auto const&dsc=discovered[static_cast<std::size_t>(discoveredIndex)];Project before=project;PluginInstance pl;pl.format=dsc.format;pl.identifier=dsc.identifier;pl.name=dsc.name;pl.bypass=true;t->mixer.plugins.push_back(pl);commit(std::move(before),"Add external plugin slot");status="Added "+dsc.name+" as a bypassed "+dsc.format+" slot; execution needs a registered production backend";refreshPhase5();}
 void showHealth(){healthIssues=validateProject(project);int errors=0;for(auto const&i:healthIssues)if(i.error)++errors;if(healthIssues.empty())status="Project Health: no structural issues found";else status="Project Health: "+std::to_string(healthIssues.size())+" issues ("+std::to_string(errors)+" errors)";}
 void runSelectedCommand(){auto*c=selectedCommand();if(!c)return;Project before=project;std::string result;if(!executeWorkflowCommand(project,c->id,0,result)){project=before;status=result;return;}commit(std::move(before),"Command: "+c->title);status=result+" | Undo available";refreshPhase5();}
 void drawPhase5Panel(){
  const auto panel=rgb(d,22,24,29),panel2=rgb(d,39,42,50),txt=rgb(d,232,234,239),muted=rgb(d,145,151,163),green=rgb(d,47,202,132),orange=rgb(d,235,151,62),purple=rgb(d,101,80,220),blue=rgb(d,61,143,230),red=rgb(d,225,72,78);
  fill(d,win,gc,phase5Toggle,phase5Mode?purple:panel2);text(d,win,gc,phase5Toggle.x+8,phase5Toggle.y+19,phase5Mode?"CLOSE PHASE 5":"ASSIST / PLUGINS [I]",txt);if(!phase5Mode){XFlush(d);return;}auto box=phase5Panel();fill(d,win,gc,box,panel);auto button=[&](Rect r,const std::string&s,unsigned long c=0UL){fill(d,win,gc,r,c?c:panel2);text(d,win,gc,r.x+6,r.y+18,s,txt);};
  text(d,win,gc,box.x+14,box.y+25,"PHASE 5 - CONTEXT ASSIST / PLUGIN HOST / ADVANCED WORKFLOW",muted);button(suggestPrev,"<");button(suggestNext,">");button(applySuggest,"APPLY + UNDO",green);button(healthButton,"HEALTH",blue);button(scanButton,"SCAN VST/AU",orange);button(addExternal,"ADD EXT SLOT",panel2);
  auto*s=selectedSuggestion();text(d,win,gc,245,455,s?"ASSIST: "+shortName(s->title,44):"ASSIST: project looks structurally clean",txt);text(d,win,gc,245,477,s?shortName(s->detail,120):"No contextual recommendation is currently required.",muted);if(s)text(d,win,gc,245,499,"ACTION: "+s->actionLabel+(s->action==AssistantAction::None?" (informational)":" (explicit edit only)"),s->action==AssistantAction::None?muted:green);
  button(masterGain,"MASTER GAIN");button(masterClip,"MASTER CLIP");button(masterWidth,"MASTER WIDTH");button(trackGain,"TRACK GAIN");button(pluginPrev,"<");button(pluginNext,">");button(pluginBypass,"BYPASS",orange);button(pluginRemove,"REMOVE",red);
  text(d,win,gc,245,555,"MASTER PLUGIN RACK",muted);int py=575;for(int i=0;i<static_cast<int>(project.master.plugins.size())&&i<5;++i){auto const&pl=project.master.plugins[static_cast<std::size_t>(i)];std::string state=pl.bypass?"BYPASS":"ACTIVE";text(d,win,gc,265,py+i*23,(i==masterPluginIndex?"> ":"  ")+shortName(pl.name,30)+" ["+pl.format+"] "+state,pl.bypass?muted:txt);}if(project.master.plugins.empty())text(d,win,gc,265,py,"(empty - native master rack is realtime/offline capable)",muted);
  text(d,win,gc,770,555,"EXTERNAL DISCOVERY",muted);if(discovered.empty())text(d,win,gc,790,575,"No scan results in this session.",muted);else{auto const&dp=discovered[static_cast<std::size_t>(std::clamp(discoveredIndex,0,static_cast<int>(discovered.size())-1))];text(d,win,gc,790,575,shortName(dp.name,34)+" ["+dp.format+"]",txt);text(d,win,gc,790,598,"Scanner does not execute plugin binaries.",muted);text(d,win,gc,790,621,"Imported external slots stay bypassed until a backend exists.",muted);}
  button(commandPrev,"<");button(commandNext,">");button(commandRun,"RUN + UNDO",green);auto*c=selectedCommand();text(d,win,gc,535,739,c?"COMMAND: "+shortName(c->title,42):"COMMAND: none",txt);if(c)text(d,win,gc,535,761,shortName(c->description,95),muted);
  int errors=0;for(auto const&i:healthIssues)if(i.error)++errors;text(d,win,gc,245,800,"Project Health: "+std::to_string(healthIssues.size())+" issue(s), "+std::to_string(errors)+" error(s). Assistant edits and commands never auto-run.",healthIssues.empty()?green:(errors?red:orange));XFlush(d);
 }
 void drawPhase5(){Phase4App::drawPhase4();drawPhase5Panel();}
 void handlePhase5Key(XKeyEvent&k){if(inputMode!=InputMode::Idle){Phase4App::handlePhase4Key(k);return;}KeySym ks=XLookupKeysym(&k,0);if(ks==XK_i||ks==XK_I){togglePhase5();return;}if(!phase5Mode){Phase4App::handlePhase4Key(k);return;}if(ks==XK_Left){cycleSuggestion(-1);return;}if(ks==XK_Right){cycleSuggestion(1);return;}if(ks==XK_Return){applySelectedSuggestion();return;}if(ks==XK_h||ks==XK_H){showHealth();return;}if(ks==XK_space||((k.state&ControlMask)!=0)){Phase4App::handlePhase4Key(k);return;}}
 void handlePhase5Button(XButtonEvent&e){if(phase5Toggle.contains(e.x,e.y)){if(e.button==1)togglePhase5();return;}if(!phase5Mode){Phase4App::handlePhase4Button(e);return;}if(e.button!=1)return;if(suggestPrev.contains(e.x,e.y)){cycleSuggestion(-1);return;}if(suggestNext.contains(e.x,e.y)){cycleSuggestion(1);return;}if(applySuggest.contains(e.x,e.y)){applySelectedSuggestion();return;}if(healthButton.contains(e.x,e.y)){showHealth();return;}if(scanButton.contains(e.x,e.y)){scanExternalPlugins();return;}if(addExternal.contains(e.x,e.y)){addDiscoveredPluginSlot();return;}if(masterGain.contains(e.x,e.y)){addMasterBuiltin("flow.gain");return;}if(masterClip.contains(e.x,e.y)){addMasterBuiltin("flow.softclip");return;}if(masterWidth.contains(e.x,e.y)){addMasterBuiltin("flow.width");return;}if(trackGain.contains(e.x,e.y)){addTrackGainPlugin();return;}if(pluginPrev.contains(e.x,e.y)){cycleMasterPlugin(-1);return;}if(pluginNext.contains(e.x,e.y)){cycleMasterPlugin(1);return;}if(pluginBypass.contains(e.x,e.y)){toggleMasterPluginBypass();return;}if(pluginRemove.contains(e.x,e.y)){removeMasterPlugin();return;}if(commandPrev.contains(e.x,e.y)){cycleCommand(-1);return;}if(commandNext.contains(e.x,e.y)){cycleCommand(1);return;}if(commandRun.contains(e.x,e.y)){runSelectedCommand();return;}}
 void handlePhase5Motion(XMotionEvent&e){if(!phase5Mode)Phase4App::handlePhase4Motion(e);}
 void handlePhase5Release(){if(!phase5Mode)Phase4App::handlePhase4Release();}
 int runPhase5(int argc,char**argv){d=XOpenDisplay(nullptr);if(!d){std::cerr<<"Cannot open X display\n";return 2;}int scr=DefaultScreen(d);win=XCreateSimpleWindow(d,RootWindow(d,scr),30,30,W,H,0,0,rgb(d,16,17,20));XStoreName(d,win,"FLOWDAW - Phase 5 Assist / Plugins / Workflow");gc=XCreateGC(d,win,0,nullptr);XSelectInput(d,win,ExposureMask|KeyPressMask|ButtonPressMask|ButtonReleaseMask|PointerMotionMask|StructureNotifyMask);XMapWindow(d,win);bool audioOk=engine.open(project.sampleRate,256);status=audioOk?(engine.inputAvailable()?"Audio ready | I opens Phase 5":"Audio output ready; no input | I opens Phase 5"):"Offline engine active | I opens Phase 5";publish();if(argc>1){std::filesystem::path path=argv[1];if(path.extension()==".flow")openProject(path);else importWav(path);ensureMidiPattern();}refreshPhase5();using namespace std::chrono_literals;while(running){while(XPending(d)){XEvent e;XNextEvent(d,&e);if(e.type==Expose)drawPhase5();else if(e.type==KeyPress)handlePhase5Key(e.xkey);else if(e.type==ButtonPress)handlePhase5Button(e.xbutton);else if(e.type==MotionNotify)handlePhase5Motion(e.xmotion);else if(e.type==ButtonRelease)handlePhase5Release();else if(e.type==DestroyNotify)running=false;}drawPhase5();std::this_thread::sleep_for(16ms);}if(audioRecording)toggleAudioRecording();if(recordingChops)finishChopRecording();engine.close();XFreeGC(d,gc);XDestroyWindow(d,win);XCloseDisplay(d);return 0;}
};
}
int main(int argc,char**argv){Phase5App app;return app.runPhase5(argc,argv);}
