#define main flowdaw_phase2_entry
#include "main.cpp"
#undef main

#include "flowdaw/Midi.hpp"
#include "flowdaw/NativeInstruments.hpp"

namespace {
const std::array<std::pair<const char*,const char*>,4> instrumentChoices={{{"FLOW Keys","flow_keys"},{"FLOW 808","flow_808"},{"FLOW Bass","flow_bass"},{"FLOW Lead","flow_lead"}}};
const std::array<const char*,4> scaleChoices={"minor","major","minor_pentatonic","major_pentatonic"};
const std::array<int,12> pianoOffsets={0,1,2,3,4,5,6,7,8,9,10,11};

struct Phase3App:App{
 enum class MidiDrag{Idle,Move,Resize};
 bool pianoMode=false;MidiDrag midiDrag=MidiDrag::Idle;int selectedMidiNote=-1;int pianoLowPitch=48;int pianoRows=25;int midiAnchorX=0,midiAnchorY=0;Tick midiStart=0,midiLength=0;int midiPitch=60;Project midiBefore;
 Rect pianoToggle{25,300,170,28};Rect instrumentBtn{250,350,120,26},rootMinus{380,350,26,26},rootPlus{474,350,26,26},scaleBtn{510,350,150,26},gridBtn{670,350,78,26},velMinusMidi{758,350,26,26},velPlusMidi{844,350,26,26},lenMinusMidi{880,350,26,26},lenPlusMidi{966,350,26,26},driveMinus{1010,350,26,26},drivePlus{1096,350,26,26},delayMinus{1132,350,26,26},delayPlus{1218,350,26,26},octDown{1260,350,60,26},octUp{1326,350,60,26};
 Rect pianoPanel()const{return{browserW+18,seqY-12,W-browserW-38,H-seqY-66};}
 Rect pianoGrid()const{auto p=pianoPanel();return{p.x+102,p.y+58,p.w-118,p.h-74};}

 Phase3App(){ensureMidiPattern();}
 Pattern*midiPattern(){for(auto&p:project.patterns)if(p.instrument.enabled)return&p;return nullptr;}const Pattern*midiPattern()const{for(auto const&p:project.patterns)if(p.instrument.enabled)return&p;return nullptr;}
 Track*instrumentTrack(){for(auto&t:project.tracks)if(t.name=="INSTRUMENT")return&t;return nullptr;}
 PatternPlacement*midiPlacement(){auto*t=instrumentTrack();auto*p=midiPattern();if(!t||!p)return nullptr;for(auto&pp:t->patternClips)if(pp.patternId==p->id)return&pp;return nullptr;}
 void ensureMidiPattern(){
    if(midiPattern())return;Project before=project;Pattern midi;midi.name="Melody 1";midi.stepCount=32;midi.stepsPerBeat=4;midi.instrument.enabled=true;midi.instrument.type="flow_keys";midi.instrument.gain=.78f;midi.instrument.attackMs=4;midi.instrument.releaseMs=120;midi.scaleRoot=0;midi.scaleType="minor";midi.midiGridTicks=kPPQ/4;midi.midiDefaultLengthTicks=kPPQ/2;const Id id=midi.id;project.patterns.push_back(midi);Track track;track.name="INSTRUMENT";PatternPlacement pp;pp.patternId=id;pp.repeats=4;track.patternClips.push_back(pp);project.tracks.push_back(track);undo.commit(before,project,"Create MIDI instrument track");publish();
 }
 void togglePiano(){ensureMidiPattern();pianoMode=!pianoMode;status=pianoMode?"Piano Roll - click to add notes, drag to move, drag right edge to resize, right-click delete":"Step Sequencer / Chop Mode";}
 Tick midiVisibleTicks()const{auto*p=midiPattern();return p?std::max<Tick>(kPPQ*4,p->lengthTicks()):kPPQ*8;}
 int midiPitchAtY(int y)const{auto r=pianoGrid();const int row=std::clamp((y-r.y)*pianoRows/std::max(1,r.h),0,pianoRows-1);return std::clamp(pianoLowPitch+pianoRows-1-row,0,127);}
 Tick midiTickAtX(int x)const{auto r=pianoGrid();auto*p=midiPattern();if(!p)return 0;const double u=std::clamp(static_cast<double>(x-r.x)/std::max(1,r.w),0.0,1.0);return snapMidiTick(static_cast<Tick>(std::llround(u*midiVisibleTicks())),p->midiGridTicks);}
 Rect midiNoteRect(const MidiNote&n)const{auto r=pianoGrid();const Tick total=midiVisibleTicks();const int row=pianoLowPitch+pianoRows-1-n.pitch;const int y=r.y+row*r.h/pianoRows;const int y2=r.y+(row+1)*r.h/pianoRows;const int x=r.x+static_cast<int>((static_cast<double>(n.startTick)/total)*r.w);const int x2=r.x+static_cast<int>((static_cast<double>(n.startTick+n.lengthTicks)/total)*r.w);return{x,y,std::max(5,x2-x),std::max(6,y2-y-1)};}
 int noteAt(int x,int y)const{auto*p=midiPattern();if(!p)return-1;for(int i=static_cast<int>(p->midiNotes.size())-1;i>=0;--i)if(midiNoteRect(p->midiNotes[static_cast<std::size_t>(i)]).contains(x,y))return i;return-1;}
 MidiNote*selectedNote(){auto*p=midiPattern();return p&&selectedMidiNote>=0&&selectedMidiNote<static_cast<int>(p->midiNotes.size())?&p->midiNotes[static_cast<std::size_t>(selectedMidiNote)]:nullptr;}
 void addMidiNote(int x,int y){auto*p=midiPattern();if(!p)return;Project before=project;MidiNote n;n.startTick=midiTickAtX(x);n.lengthTicks=p->midiDefaultLengthTicks;n.pitch=midiPitchAtY(y);n.velocity=.9f;p->midiNotes.push_back(n);selectedMidiNote=static_cast<int>(p->midiNotes.size())-1;commit(std::move(before),"Add MIDI note");previewPitch(n.pitch);status="Added "+midiNoteName(n.pitch);}
 void deleteSelectedMidi(){auto*p=midiPattern();if(!p||selectedMidiNote<0||selectedMidiNote>=static_cast<int>(p->midiNotes.size()))return;Project before=project;const auto name=midiNoteName(p->midiNotes[static_cast<std::size_t>(selectedMidiNote)].pitch);p->midiNotes.erase(p->midiNotes.begin()+selectedMidiNote);selectedMidiNote=std::min(selectedMidiNote,static_cast<int>(p->midiNotes.size())-1);commit(std::move(before),"Delete MIDI note");status="Deleted "+name;}
 void adjustMidiNote(float velocityDelta,Tick lengthDelta){auto*n=selectedNote();auto*p=midiPattern();if(!n||!p)return;Project before=project;n->velocity=std::clamp(n->velocity+velocityDelta,0.05f,1.5f);n->lengthTicks=std::max<Tick>(p->midiGridTicks/2,n->lengthTicks+lengthDelta);commit(std::move(before),"Edit MIDI note");}
 void nudgeSelected(Tick dt,int dp){auto*n=selectedNote();auto*p=midiPattern();if(!n||!p)return;Project before=project;n->startTick=snapMidiTick(std::max<Tick>(0,n->startTick+dt),p->midiGridTicks);n->pitch=std::clamp(n->pitch+dp,0,127);commit(std::move(before),"Nudge MIDI note");previewPitch(n->pitch);}
 void cycleInstrument(){auto*p=midiPattern();if(!p)return;int idx=0;for(int i=0;i<static_cast<int>(instrumentChoices.size());++i)if(p->instrument.type==instrumentChoices[static_cast<std::size_t>(i)].second)idx=i;Project before=project;idx=(idx+1)%static_cast<int>(instrumentChoices.size());p->instrument.type=instrumentChoices[static_cast<std::size_t>(idx)].second;commit(std::move(before),"Change native instrument");status=instrumentChoices[static_cast<std::size_t>(idx)].first;}
 void cycleScale(){auto*p=midiPattern();if(!p)return;int idx=0;for(int i=0;i<static_cast<int>(scaleChoices.size());++i)if(p->scaleType==scaleChoices[static_cast<std::size_t>(i)])idx=i;Project before=project;p->scaleType=scaleChoices[static_cast<std::size_t>((idx+1)%static_cast<int>(scaleChoices.size()))];commit(std::move(before),"Change scale");}
 void adjustScaleRoot(int delta){auto*p=midiPattern();if(!p)return;Project before=project;p->scaleRoot=(p->scaleRoot+delta+12)%12;commit(std::move(before),"Change scale root");}
 void cycleMidiGrid(){auto*p=midiPattern();if(!p)return;Project before=project;p->midiGridTicks=p->midiGridTicks==kPPQ/2?kPPQ/4:(p->midiGridTicks==kPPQ/4?kPPQ/8:kPPQ/2);commit(std::move(before),"Change MIDI grid");}
 void adjustInstrument(float drive,float delay){auto*p=midiPattern();if(!p)return;Project before=project;p->instrument.drive=std::clamp(p->instrument.drive+drive,0.0f,1.0f);p->instrument.delayMix=std::clamp(p->instrument.delayMix+delay,0.0f,.8f);commit(std::move(before),"Edit instrument FX");}
 void previewPitch(int pitch){auto*p=midiPattern();if(!p)return;const auto frames=MusicalTime::ticksToSamples(std::max<Tick>(p->midiDefaultLengthTicks,kPPQ/4),project.transport.bpm,project.sampleRate);auto audio=std::make_shared<AudioBuffer>(renderNativeInstrumentNote(p->instrument,pitch,1.0f,frames,project.sampleRate,project.transport.bpm));engine.triggerPreview(audio,0,audio->frames(),p->instrument.gain,p->instrument.pan,0);status="Preview "+midiNoteName(pitch);}
 int keyboardPitch(KeySym ks)const{int off=-1;switch(ks){case XK_a:off=0;break;case XK_w:off=1;break;case XK_s:off=2;break;case XK_e:off=3;break;case XK_d:off=4;break;case XK_f:off=5;break;case XK_t:off=6;break;case XK_g:off=7;break;case XK_y:off=8;break;case XK_h:off=9;break;case XK_u:off=10;break;case XK_j:off=11;break;default:break;}return off<0?-1:60+off;}

 void drawPianoOverlay(){
    const auto panel=rgb(d,27,29,34),panel2=rgb(d,37,40,47),txt=rgb(d,230,232,237),muted=rgb(d,145,151,163),grid=rgb(d,55,60,69),off=rgb(d,49,52,60),green=rgb(d,48,202,132),purple=rgb(d,96,78,220),orange=rgb(d,237,150,60),blue=rgb(d,62,145,230),rootCol=rgb(d,54,73,78),scaleCol=rgb(d,38,48,51),black=rgb(d,29,31,36);
    fill(d,win,gc,pianoToggle,pianoMode?purple:panel2);text(d,win,gc,pianoToggle.x+9,pianoToggle.y+19,pianoMode?"CLOSE PIANO ROLL":"PIANO ROLL  [P]",txt);if(!pianoMode){XFlush(d);return;}auto*p=midiPattern();if(!p)return;auto box=pianoPanel();fill(d,win,gc,box,panel);text(d,win,gc,box.x+14,box.y+22,"PIANO ROLL / MIDI",muted);
    auto button=[&](Rect r,const std::string&s,unsigned long c=0UL){fill(d,win,gc,r,c?c:panel2);text(d,win,gc,r.x+6,r.y+18,s,txt);};
    std::string inst="FLOW Keys";for(auto const&v:instrumentChoices)if(p->instrument.type==v.second)inst=v.first;button(instrumentBtn,inst,blue);button(rootMinus,"-");button(rootPlus,"+");static const char* roots[12]={"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"};text(d,win,gc,410,368,std::string("Root ")+roots[p->scaleRoot],txt);button(scaleBtn,p->scaleType);button(gridBtn,gridLabel(p->midiGridTicks));button(velMinusMidi,"-");button(velPlusMidi,"+");text(d,win,gc,790,368,"VEL",muted);button(lenMinusMidi,"-");button(lenPlusMidi,"+");text(d,win,gc,912,368,"LEN",muted);button(driveMinus,"-");button(drivePlus,"+");text(d,win,gc,1040,368,"DRV "+std::to_string(static_cast<int>(p->instrument.drive*100)),muted);button(delayMinus,"-");button(delayPlus,"+");text(d,win,gc,1162,368,"DLY "+std::to_string(static_cast<int>(p->instrument.delayMix*100)),muted);button(octDown,"OCT-");button(octUp,"OCT+");
    auto r=pianoGrid();for(int row=0;row<pianoRows;++row){const int pitch=pianoLowPitch+pianoRows-1-row;const int y=r.y+row*r.h/pianoRows,y2=r.y+(row+1)*r.h/pianoRows;const int pc=pitch%12;const bool blackKey=pc==1||pc==3||pc==6||pc==8||pc==10;const bool inScale=pitchInScale(pitch,p->scaleRoot,p->scaleType);const bool root=pc==p->scaleRoot;fill(d,win,gc,{r.x-92,y,88,std::max(1,y2-y-1)},blackKey?black:off);if(pc==0||row==pianoRows-1)text(d,win,gc,r.x-84,y+12,midiNoteName(pitch),txt);fill(d,win,gc,{r.x,y,r.w,std::max(1,y2-y)},root?rootCol:(inScale?scaleCol:rgb(d,22,24,28)));line(d,win,gc,r.x,y2,r.x+r.w,y2,grid);}
    const Tick total=midiVisibleTicks();for(Tick t=0;t<=total;t+=std::max<Tick>(1,p->midiGridTicks)){const int x=r.x+static_cast<int>((static_cast<double>(t)/total)*r.w);const bool beat=t%kPPQ==0,bar=t%(kPPQ*4)==0;line(d,win,gc,x,r.y,x,r.y+r.h,bar?orange:(beat?grid:rgb(d,42,45,52)));if(bar)text(d,win,gc,x+3,r.y-5,std::to_string(t/(kPPQ*4)+1),muted);}
    for(int i=0;i<static_cast<int>(p->midiNotes.size());++i){auto const&n=p->midiNotes[static_cast<std::size_t>(i)];if(n.pitch<pianoLowPitch||n.pitch>=pianoLowPitch+pianoRows)continue;auto nr=midiNoteRect(n);fill(d,win,gc,nr,i==selectedMidiNote?green:purple);text(d,win,gc,nr.x+4,nr.y+12,midiNoteName(n.pitch),txt);line(d,win,gc,nr.x+nr.w-3,nr.y,nr.x+nr.w-3,nr.y+nr.h,orange);}
    if(auto*n=selectedNote())text(d,win,gc,r.x,r.y+r.h+18,"Selected "+midiNoteName(n->pitch)+" | start "+std::to_string(n->startTick)+"t | len "+std::to_string(n->lengthTicks)+"t | vel "+std::to_string(static_cast<int>(n->velocity*100))+"%",txt);else text(d,win,gc,r.x,r.y+r.h+18,"Click grid: add | drag: move | edge drag: resize | right-click: delete | A-W-S-E-D-F-T-G-Y-H-U-J: preview",muted);XFlush(d);
 }
 void drawPhase3(){App::draw();drawPianoOverlay();}

 void handleMidiKey(XKeyEvent&k){if(inputMode!=InputMode::Idle){App::handleKey(k);return;}KeySym ks=XLookupKeysym(&k,0);bool ctrl=(k.state&ControlMask)!=0,shift=(k.state&ShiftMask)!=0;if(ks==XK_p||ks==XK_P){togglePiano();return;}if(!pianoMode){App::handleKey(k);return;}if(ctrl||ks==XK_space||ks==XK_Escape){App::handleKey(k);return;}if(ks==XK_Delete||ks==XK_BackSpace){deleteSelectedMidi();return;}if(ks==XK_Left){nudgeSelected(-midiPattern()->midiGridTicks,0);return;}if(ks==XK_Right){nudgeSelected(midiPattern()->midiGridTicks,0);return;}if(ks==XK_Up){if(shift)adjustMidiNote(.05f,0);else nudgeSelected(0,1);return;}if(ks==XK_Down){if(shift)adjustMidiNote(-.05f,0);else nudgeSelected(0,-1);return;}int pitch=keyboardPitch(ks);if(pitch>=0){previewPitch(pitch);return;}if(ks==XK_bracketleft){pianoLowPitch=std::max(0,pianoLowPitch-12);return;}if(ks==XK_bracketright){pianoLowPitch=std::min(103,pianoLowPitch+12);return;}App::handleKey(k);}
 void handleMidiButton(XButtonEvent&e){if(pianoToggle.contains(e.x,e.y)){if(e.button==1)togglePiano();return;}if(!pianoMode||e.y<pianoPanel().y){App::handleButton(e);return;}if(e.button==1){if(instrumentBtn.contains(e.x,e.y)){cycleInstrument();return;}if(rootMinus.contains(e.x,e.y)){adjustScaleRoot(-1);return;}if(rootPlus.contains(e.x,e.y)){adjustScaleRoot(1);return;}if(scaleBtn.contains(e.x,e.y)){cycleScale();return;}if(gridBtn.contains(e.x,e.y)){cycleMidiGrid();return;}if(velMinusMidi.contains(e.x,e.y)){adjustMidiNote(-.05f,0);return;}if(velPlusMidi.contains(e.x,e.y)){adjustMidiNote(.05f,0);return;}if(lenMinusMidi.contains(e.x,e.y)){adjustMidiNote(0,-midiPattern()->midiGridTicks);return;}if(lenPlusMidi.contains(e.x,e.y)){adjustMidiNote(0,midiPattern()->midiGridTicks);return;}if(driveMinus.contains(e.x,e.y)){adjustInstrument(-.05f,0);return;}if(drivePlus.contains(e.x,e.y)){adjustInstrument(.05f,0);return;}if(delayMinus.contains(e.x,e.y)){adjustInstrument(0,-.05f);return;}if(delayPlus.contains(e.x,e.y)){adjustInstrument(0,.05f);return;}if(octDown.contains(e.x,e.y)){pianoLowPitch=std::max(0,pianoLowPitch-12);return;}if(octUp.contains(e.x,e.y)){pianoLowPitch=std::min(103,pianoLowPitch+12);return;}}
    auto r=pianoGrid();if(!r.contains(e.x,e.y))return;int hit=noteAt(e.x,e.y);if(e.button==3){if(hit>=0){selectedMidiNote=hit;deleteSelectedMidi();}return;}if(e.button!=1)return;if(hit<0){addMidiNote(e.x,e.y);return;}selectedMidiNote=hit;auto*n=selectedNote();if(!n)return;auto nr=midiNoteRect(*n);midiDrag=(e.x>=nr.x+nr.w-7)?MidiDrag::Resize:MidiDrag::Move;midiAnchorX=e.x;midiAnchorY=e.y;midiStart=n->startTick;midiLength=n->lengthTicks;midiPitch=n->pitch;midiBefore=project;previewPitch(n->pitch);
 }
 void handleMidiMotion(XMotionEvent&e){if(!pianoMode||midiDrag==MidiDrag::Idle){App::handleMotion(e);return;}auto*n=selectedNote();auto*p=midiPattern();if(!n||!p)return;auto r=pianoGrid();const Tick dt=snapMidiTick(static_cast<Tick>(std::llround((e.x-midiAnchorX)*static_cast<double>(midiVisibleTicks())/std::max(1,r.w))),p->midiGridTicks);if(midiDrag==MidiDrag::Resize)n->lengthTicks=std::max<Tick>(p->midiGridTicks/2,midiLength+dt);else{n->startTick=snapMidiTick(std::max<Tick>(0,midiStart+dt),p->midiGridTicks);const int rowDelta=static_cast<int>(std::llround((midiAnchorY-e.y)*static_cast<double>(pianoRows)/std::max(1,r.h)));n->pitch=std::clamp(midiPitch+rowDelta,0,127);}publish();}
 void handleMidiRelease(){if(midiDrag!=MidiDrag::Idle){undo.commit(midiBefore,project,midiDrag==MidiDrag::Resize?"Resize MIDI note":"Move MIDI note");publish();midiDrag=MidiDrag::Idle;status="MIDI note edited";return;}App::handleRelease();}

 int runPhase3(int argc,char**argv){d=XOpenDisplay(nullptr);if(!d){std::cerr<<"Cannot open X display\n";return 2;}int scr=DefaultScreen(d);win=XCreateSimpleWindow(d,RootWindow(d,scr),30,30,W,H,0,0,rgb(d,16,17,20));XStoreName(d,win,"FLOWDAW - Phase 3 Piano Roll / MIDI / Instruments");gc=XCreateGC(d,win,0,nullptr);XSelectInput(d,win,ExposureMask|KeyPressMask|ButtonPressMask|ButtonReleaseMask|PointerMotionMask|StructureNotifyMask);XMapWindow(d,win);bool audioOk=engine.open(project.sampleRate,256);status=audioOk?"Audio device ready | P opens Piano Roll":"No physical audio device; deterministic engine active | P opens Piano Roll";publish();if(argc>1){std::filesystem::path path=argv[1];if(path.extension()==".flow")openProject(path);else importWav(path);}using namespace std::chrono_literals;while(running){while(XPending(d)){XEvent e;XNextEvent(d,&e);if(e.type==Expose)drawPhase3();else if(e.type==KeyPress)handleMidiKey(e.xkey);else if(e.type==ButtonPress)handleMidiButton(e.xbutton);else if(e.type==MotionNotify)handleMidiMotion(e.xmotion);else if(e.type==ButtonRelease)handleMidiRelease();else if(e.type==DestroyNotify)running=false;}drawPhase3();std::this_thread::sleep_for(16ms);}if(recordingChops)finishChopRecording();engine.close();XFreeGC(d,gc);XDestroyWindow(d,win);XCloseDisplay(d);return 0;}
};
}

int main(int argc,char**argv){Phase3App app;return app.runPhase3(argc,argv);}
